-- MySQL Script generated by MySQL Workbench
-- Mon Nov 16 19:14:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Port_DW
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Port_DW` ;

-- -----------------------------------------------------
-- Schema Port_DW
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Port_DW` DEFAULT CHARACTER SET utf8 ;
USE `Port_DW` ;

-- -----------------------------------------------------
-- Table `Port_DW`.`Product_Dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Port_DW`.`Product_Dimension` ;

CREATE TABLE IF NOT EXISTS `Port_DW`.`Product_Dimension` (
  `Product_Key` INT NOT NULL AUTO_INCREMENT,
  `Product_ID` INT NOT NULL,
  `Product_Measure` VARCHAR(30) NOT NULL COMMENT 'Ton, Container, Kg, Liter, etc.',
  `Bulk_OR_Container` TINYINT NOT NULL,
  `Product_Name` VARCHAR(130) NOT NULL,
  `Product_Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Product_Key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Port_DW`.`Port_Dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Port_DW`.`Port_Dimension` ;

CREATE TABLE IF NOT EXISTS `Port_DW`.`Port_Dimension` (
  `Port_Key` INT NOT NULL AUTO_INCREMENT,
  `Port_Code` VARCHAR(5) NOT NULL,
  `Latitude` VARCHAR(45) NOT NULL,
  `Longitude` VARCHAR(45) NOT NULL,
  `Country_Code` VARCHAR(2) NOT NULL,
  `Country_Name` VARCHAR(45) NOT NULL,
  `State_Code` VARCHAR(3) NULL,
  `State_Name` VARCHAR(80) NULL,
  `State_Type` VARCHAR(60) NULL,
  PRIMARY KEY (`Port_Key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Port_DW`.`Vendor_Dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Port_DW`.`Vendor_Dimension` ;

CREATE TABLE IF NOT EXISTS `Port_DW`.`Vendor_Dimension` (
  `Vendor_Key` INT NOT NULL AUTO_INCREMENT,
  `Vendor_ID` INT NOT NULL,
  `Vendor_Name` VARCHAR(50) NOT NULL,
  `Contact_Person` VARCHAR(25) NULL,
  `Email` VARCHAR(35) NULL,
  `Phone` VARCHAR(20) NULL,
  `Country_Code` VARCHAR(2) NULL,
  `Country_Name` VARCHAR(45) NULL,
  `State_Code` VARCHAR(3) NULL,
  `State_Name` VARCHAR(80) NULL,
  `State_Type` VARCHAR(60) NULL,
  PRIMARY KEY (`Vendor_Key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Port_DW`.`Date_Dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Port_DW`.`Date_Dimension` ;

CREATE TABLE IF NOT EXISTS `Port_DW`.`Date_Dimension` (
  `Date_Key` INT NOT NULL AUTO_INCREMENT,
  `Day` INT NOT NULL,
  `Month` INT NOT NULL,
  `Year` INT NOT NULL,
  `Quarter` INT NOT NULL,
  PRIMARY KEY (`Date_Key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Port_DW`.`Time_Dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Port_DW`.`Time_Dimension` ;

CREATE TABLE IF NOT EXISTS `Port_DW`.`Time_Dimension` (
  `Time_Key` INT NOT NULL AUTO_INCREMENT,
  `Minute` INT NOT NULL,
  `Hour` INT NOT NULL,
  PRIMARY KEY (`Time_Key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Port_DW`.`Timezone_Dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Port_DW`.`Timezone_Dimension` ;

CREATE TABLE IF NOT EXISTS `Port_DW`.`Timezone_Dimension` (
  `Timezone_Key` INT NOT NULL AUTO_INCREMENT,
  `Timezone_UTC_Offset` INT NOT NULL,
  PRIMARY KEY (`Timezone_Key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Port_DW`.`Shipment_Fact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Port_DW`.`Shipment_Fact` ;

CREATE TABLE IF NOT EXISTS `Port_DW`.`Shipment_Fact` (
  `Shipment_Fact _Key` INT NOT NULL AUTO_INCREMENT,
  `Quantity` INT NOT NULL,
  `Product` INT NOT NULL,
  `Origin` INT NOT NULL,
  `Destination` INT NOT NULL,
  `Vendor` INT NOT NULL,
  `Date_Departed` INT NOT NULL,
  `Time_Departed` INT NOT NULL,
  `Timezone_Departed` INT NOT NULL,
  `Date_Arrived` INT NOT NULL,
  `Time_Arrived` INT NOT NULL,
  `Timezone_Arrived` INT NOT NULL,
  PRIMARY KEY (`Shipment_Fact _Key`),
  INDEX `fk_Shipment Fact_Product Dimension_idx` (`Product` ASC) VISIBLE,
  INDEX `fk_Shipment Fact_Port Dimension2_idx` (`Origin` ASC) VISIBLE,
  INDEX `fk_Shipment Fact_Port Dimension1_idx` (`Destination` ASC) VISIBLE,
  INDEX `fk_Shipment Fact_Vendor Dimension1_idx` (`Vendor` ASC) VISIBLE,
  INDEX `fk_Shipment Fact_Date Dimension1_idx` (`Date_Departed` ASC) VISIBLE,
  INDEX `fk_Shipment Fact_Time Dimension1_idx` (`Time_Departed` ASC) VISIBLE,
  INDEX `fk_Shipment Fact_Timezone Dimension1_idx` (`Timezone_Departed` ASC) VISIBLE,
  INDEX `fk_Shipment Fact_Date Dimension2_idx` (`Date_Arrived` ASC) VISIBLE,
  INDEX `fk_Shipment Fact_Time Dimension2_idx` (`Time_Arrived` ASC) VISIBLE,
  INDEX `fk_Shipment Fact_Timezone Dimension2_idx` (`Timezone_Arrived` ASC) VISIBLE,
  CONSTRAINT `fk_Shipment Fact_Product Dimension`
    FOREIGN KEY (`Product`)
    REFERENCES `Port_DW`.`Product_Dimension` (`Product_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shipment Fact_Port Dimension2`
    FOREIGN KEY (`Origin`)
    REFERENCES `Port_DW`.`Port_Dimension` (`Port_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shipment Fact_Port Dimension1`
    FOREIGN KEY (`Destination`)
    REFERENCES `Port_DW`.`Port_Dimension` (`Port_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shipment Fact_Vendor Dimension1`
    FOREIGN KEY (`Vendor`)
    REFERENCES `Port_DW`.`Vendor_Dimension` (`Vendor_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shipment Fact_Date Dimension1`
    FOREIGN KEY (`Date_Departed`)
    REFERENCES `Port_DW`.`Date_Dimension` (`Date_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shipment Fact_Time Dimension1`
    FOREIGN KEY (`Time_Departed`)
    REFERENCES `Port_DW`.`Time_Dimension` (`Time_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shipment Fact_Timezone Dimension1`
    FOREIGN KEY (`Timezone_Departed`)
    REFERENCES `Port_DW`.`Timezone_Dimension` (`Timezone_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shipment Fact_Date Dimension2`
    FOREIGN KEY (`Date_Arrived`)
    REFERENCES `Port_DW`.`Date_Dimension` (`Date_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shipment Fact_Time Dimension2`
    FOREIGN KEY (`Time_Arrived`)
    REFERENCES `Port_DW`.`Time_Dimension` (`Time_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shipment Fact_Timezone Dimension2`
    FOREIGN KEY (`Timezone_Arrived`)
    REFERENCES `Port_DW`.`Timezone_Dimension` (`Timezone_Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
